---

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ind_user: "admin"
    ind_password: "cisco123"
    indurl: "https://198.18.135.62:8443"
    csvfile: "devices.csv"
    listy:
      - { name: 'name1', group: 'wheel'}
      - { name: 'name2', group: 'wheel2'}
  tasks:

    - name: csv-read
      read_csv:
        path: "{{ csvfile }}"
        delimiter: ';'
      register: devices

    - name: add-discovery
      uri:
        method: POST
        url: "{{ indurl }}/api/v1/discovery-profiles"
        user: "{{ ind_user }}"
        password: "{{ ind_password }}"
        force_basic_auth: yes
        validate_certs: no
        body:
          accessProfileId: "{{ item.accessProfileId }}" # (integer) Access profile ID to associate the discovery profile
          isLinkLayerDiscovery: false # (boolean) Type of discovery profile (Link layer discovery or IP scan discovery) ,
          name: "{{ item.name }}" # (string) Internationalized discovery profile name
          startIp: "{{ item.startip }}" # (string) Start IPv4 address of the discovery profile
          endIp: "{{ item.endip}}" # (string) End IPv4 address of the discovery profile
          netmask: "{{ item.netmask}}"
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        timeout: 10
        body_format: json
      # Loop over csv list
      loop: "{{ devices.list }}"
      register: http_output

    - debug:
            var: http_output
